import { combineReducers } from "redux";
import {
  fetchCategories,
  fetchProjectList,
  fetchDefiLendingList,
  fetchWeb3Data,
  fetchFearNGreedIndex,
  fetchDuneAnalytics,
  fetchUserBalances,
  fetchMetamask,
  fetchSelectedProjectDetails,
  fetchProjectGraph,
  fetchPriceTrendGraph,
  fetchTweetAnalysis,
  fetchDefiGraphData,
  fetchThirdPartyDefiList,
  getSocialData,
  fetchAccessibility,
  fetchNullStakingPool,
  fetchMMWindowStatus,
} from "./defi.reducer";
import {
  fetchRookieContractInstance,
  fetchTokenContractInstance,
  fetchUserMetamaskTotalBalances,
  fetchLegendaryContractInstance,
  fetchProfessionalContractInstance,
  fetchLiquidityTokenContractInstance,
  fetchLiquidityContractInstance,
  riskType,
  defaultProvider,
  providers,
  fetchNetworkId,
  fetchNabox,
} from "./web3.reducer";
const rootReducer = combineReducers({
  fetchNetworkId,
  fetchMMWindowStatus,
  fetchNullStakingPool,
  fetchAccessibility,
  fetchCategories,
  fetchProjectList,
  fetchDefiLendingList,
  fetchWeb3Data,
  fetchFearNGreedIndex,
  fetchDuneAnalytics,
  fetchMetamask,
  fetchUserBalances,
  fetchSelectedProjectDetails,
  fetchProjectGraph,
  fetchPriceTrendGraph,
  fetchTweetAnalysis,
  fetchDefiGraphData,
  fetchRookieContractInstance,
  fetchTokenContractInstance,
  fetchUserMetamaskTotalBalances,
  fetchLegendaryContractInstance,
  fetchProfessionalContractInstance,
  fetchThirdPartyDefiList,
  getSocialData,
  riskType,
  fetchLiquidityContractInstance,
  fetchLiquidityTokenContractInstance,
  defaultProvider,
  providers,
  fetchNabox,
});

export default rootReducer;
